# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-FromHTML
version:      0.041
version_from: lib/XML/RSS/FromHTML.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    File::Temp:                    0
    HTML::Entities:                1.35
    HTTP::Cookies:                 0
    HTTP::Date:                    0
    LWP::UserAgent:                0
    Test::More:                    0
    Test::Simple:                  0.44
    XML::Parser:                   2.34
    XML::RSS:                      1.43

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
