--- #YAML:1.0
name:               XML-RSS-FromHTML
version:            0.06
abstract:           simple framework for creating RSS out of HTML
author:
    - Toshimasa Ishibashi (bashi@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    File::Temp:           0
    HTML::Parser:         3.68
    HTTP::Cookies:        0
    HTTP::Date:           0
    LWP::UserAgent:       0
    Test::More:           0
    Test::Simple:         0.44
    XML::Parser:          2.36
    XML::RSS:             1.48
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
